name: RolesSyncBot
version: ${project.version}
main: com.veysure.rbw.ingame.sync.RolesSyncBot
api-version: 1.20
author: veysure
description: Syncs Discord roles with LuckPerms groups on join.
depend: [LuckPerms]

commands:
  rolesync:
    description: Manage role sync settings
    usage: /rolesync <reload|sync <player>>
    permission: rolesync.admin

permissions:
  rolesync.admin:
    description: Allows use of /rolesync commands
    default: op
